/*
 Copyright 2017 Webtrends Inc. All Rights Reserved.
 WEBTRENDS PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.

 For information on libraries used by the Webtrends Infinity Tag, please see
 the following link: https://producthelp.webtrends.com/data-collection/third-party-libraries/
*/
(function(f,k,p,v){function s(f,n,k,v){var s=this,x={major:1,minor:0,inc:3},e=this,p=!1,H=2E3,C="undefined"!=typeof _wt_forceSSL&&_wt_forceSSL?"https:":"https:"==document.location.protocol?"https:":"http:",M="sizzle",I=null,J=!1,D=!1,y=!1;this.isBodyExtant=function(){try{return"undefined"!=typeof document.getElementsByTagName("body")[0]?!0:!1}catch(a){return WT.Debug.error("isBodyExtant: body detection fail, assuming false","002",a),!1}};this.inHead=function(){return y};this.getSelector=function(){switch(M){case "sizzle":if("undefined"!==
typeof Sizzle&&WT.hasVal(Sizzle))return Sizzle;if("undefined"!==typeof WT.Sizzle)return WT.Sizzle;default:if(null!==I)return I;WT.Debug.error("getSelector:  No Selector found","003");return null}};this.setCustomSelector=function(a,b){M=a;I=b};this.applyStyleSheet=function(a,b){try{var c=n.getElementsByTagName("head")[0],h=n.createElement("style");h.type="text/css";h.id=b;h.styleSheet?h.styleSheet.cssText=a:h.appendChild(n.createTextNode(a));c.appendChild(h)}catch(g){WT.Debug.error("applyStyleSheet:  Failed to failed to apply stylesheet",
"004",g)}};this.removeStyleSheet=function(a){try{var b=n.getElementById(a);"undefined"!==typeof b&&null!==b&&b.parentNode.removeChild(b)}catch(c){WT.Debug.debug("removeStyleSheet:  Failed to remove stylesheet")}};this.redirectElement=function(a,b){b&&WT.Debug.debug(b);null!==a&&a.wt_pending&&"true"===a.wt_pending?(WT.Debug.info("click: redirecting to url ["+a.wt_href+"]"),a.href=a.wt_href,a.target=a.wt_target,a.wt_pending="","undefined"!==typeof a.wt_target&&""!==a.wt_target&&null!==a.wt_target?window.open(a.wt_href,
a.wt_target):setTimeout(function(){window.location.href=a.wt_href},0)):WT.Debug.debug("click: redirect not pending or !elm, so not redirecting")};this.hasVal=function(a){return null!==a&&"undefined"!==typeof a?!0:!1};var w=function(){J||(J=!0,WT.fireEvent(new WT.Event(WT.Event.DOM_READY,WT.Event.STATUS_SUCCESS),!0))},E=function(){D||(D=!0,WT.fireEvent(new WT.Event(WT.Event.DOM_ONLOAD,WT.Event.STATUS_SUCCESS),!0))},F=function(a){return"undefined"!==typeof t&&"undefined"!==typeof d[a].contextName&&
"undefined"!==typeof t[a]&&t[a]===d[a].contextName?(e.Debug.trace("LOADER:  context '"+d[a].contextName+"' triggered for "+a),!0):"undefined"===typeof t||"undefined"===typeof t[a]?(e.Debug.trace("LOADER:  published context triggered for "+a),!0):!1},z=function(a,b){e.fireEvent(new WT.Event(a,WT.Event.STATUS_SUCCESS,null,b),null,null,!0)};this.collect=function(a){z(WT.Event.LOADER_COLLECT,a);return 1};this.view=function(a){z(WT.Event.LOADER_VIEW,a);return 1};this.click=function(a,b){try{var c=2;if("undefined"!==
typeof a&&a&&"object"==typeof a){var h,g;a.type?(h=a,g=a.currentTarget?a.currentTarget:a.srcElement):a.tagName&&(g=a);h&&(h.preventDefault?h.preventDefault():h.returnValue=!1);if(g){if(g.href){g.wt_pending||(g.wt_pending="true",g.wt_href=g.href,g.wt_target=g.target,g.href="javascript:void(0);",g.target="");b.r_redirectLink=g;var e=b.s_conversionTimeout?b.s_conversionTimeout:H;setTimeout(function(){WT.Debug.info("Click: timed out after "+e);redirectElement(g)},e)}}else b=a,c=1}Array.prototype.slice.call(arguments,
c);z(WT.Event.LOADER_CLICK,b)}catch(l){"object"==typeof a&&a.href&&b.r_redirectLink===a&&(a.href=a.wt_href,a.target=a.wt_target),WT.Debug.error("Click: Fatal error, check error message for details.","005",l)}};this.reset=function(){for(var a in d)d.hasOwnProperty(a)&&d[a].reset();z(WT.Event.LOADER_RESET,null)};this.execute=function(a){Array.prototype.slice.call(arguments,1);z(WT.Event.LOADER_PRE_EXECUTE,a);z(WT.Event.LOADER_EXECUTE,a)};this.loaderConversionTimeoutDefault=function(){return H};this.setLoaderConversionTimeoutDefault=
function(a){H=a};this.startTimer=function(a,b){WT.hasVal(d[a])&&(e.Debug.trace("LOADER:  api starting timer for "+b+" ms on "+a),WT.hasVal(b)?d[a]._startTimer(b):d[a]._startTimer(1E4))};this.clearTimer=function(a){d[a]&&(e.Debug.trace("LOADER:  loader clearing timer for "+a),d[a]._clearTimer(),e.fireEvent(new WT.Event(a+"_"+WT.Event.TIMER_CLEAR,WT.Event.STATUS_SUCCESS)))};this.pollForCondition=function(a,b,c){var h=function(a,b,c,d){setTimeout(function(){d--;a()?(e.Debug.trace("pollForCondition success result\x3d"+
a(),"LOADER"),e.Debug.superfine("pollForCondition success condition\x3d"+a.toString(),"LOADER"),b&&(b(),e.Debug.trace("pollForCondition running callback","LOADER"),e.Debug.superfine("pollForCondition callback\x3d"+b.toString(),"LOADER"))):0<d?h(a,b,c,d):(e.Debug.error("pollForCondition Fail on "+a.toString(),"009"),c&&(c(),e.Debug.superfine("pollForCondition callbackFailure\x3d"+c.toString(),"LOADER")))},e.s_pollInterval)};h(a,b,c,100)};this.paramsMerge=function(a,b,c){var h={};if(WT.hasVal(a))for(var g in a)a.hasOwnProperty(g)&&
(h[g]=a[g]);for(var e in b)WT.hasVal(b[e])&&b.hasOwnProperty(e)&&(WT.hasVal(c)&&WT.hasVal(c[e])?h[e]=c[e]:h[e]=b[e]);return h};this.downloadLib=function(a,b,c,h,g,d){e.Debug.info("LOADER:  Start download: "+C+d+" \x26 attach to "+a+", async\x3d"+g);setTimeout(function(){var h=n.getElementsByTagName(a)[0],m=n.createElement("script");m.type="text/javascript";m.src=C+d;m.setAttribute("async",g);m.setAttribute("defer",g);m.wtHasRun=!1;var q=function(){!1===this.wtHasRun?(b(),this.wtHasRun=!0,e.Debug.info("Completed download: "+
C+d+", callback running, set wtHasRun\x3d"+this.wtHasRun,"LOADER"),e.Debug.superfine("downloadLib: successCallback\x3d"+b.toString(),"LOADER")):e.Debug.trace("downloadLib: not running successCallback, since wtHasRun\x3d"+this.wtHasRun,"LOADER")};b&&(m.onload=q,m.onreadystatechange=q);m.onerror=function(){e.Debug.error("FAILED download: "+C+d+" \x26 attach to "+a+", async\x3d"+g,"010");c&&(c(),e.Debug.superfine("failCallback: "+c.toString(),"LOADER"))};typeof("undefined"!==h)?h.appendChild(m):e.Debug.info("LOADER:  Dom element: "+
a+" is not found so not Downloading")},h)};this.downloadLibs=function(a,b,c,h,g){if("undefined"===typeof g)e.Debug.info("LOADER:  downloadLibs srcs is empty");else{var d={},l;for(l in g)g.hasOwnProperty(l)&&(d[l]="waiting",e.Debug.trace("LOADER:  downloadLibs is waiting on src:"+l+" \x3d "+g[l]),e.downloadLib(a,function(a){return function(){d[a]="complete";e.Debug.trace("LOADER:  downloadLibs is complete src:"+a+" \x3d "+g[a])}}(l),null,c,h,g[l]));e.pollForCondition(function(){for(var a in d)if(d.hasOwnProperty(a)&&
"complete"!==d[a])return!1;return!0},function(){e.Debug.debug("LOADER:  downloadLibs completed on all downloads");b()})}};this.parseQueryString=function(a){var b=a;e.hasVal(a)&&e.hasVal(a.location)&&e.hasVal(a.location.search)||(b=document);a=function(a){var b=a.split("\x26");null!==b&&0===b.length&&(b=a.split(";"));a=b.length-1;for(var g={},e=0;e<=a;e++){var l=b[e].split("\x3d");l[0]=unescape(l[0]);l[1]=unescape(l[1]);l[0]=l[0].replace(/\+/g," ");l[1]=l[1].replace(/\+/g," ");l[1]=l[1].replace(/<.*\?>/g,
"");g[l[0]]=l[1]}return g};return b.location.search?(b=b.location.search.substring(1,b.location.search.length),a(b)):b.location.href?(b=b.location.href.split("?"),2===b.length?a(b[1]):null):null};this.abortModuleHelper=function(a,b){WT.fireEvent(new WT.Event(a+"_"+WT.Event.LOADER_MODULE_ABORT,WT.Event.STATUS_SUCCESS));WT.setExecuteState(a,WT.Event.LOADER_MODULE_ABORT);WT.clearTimer(a);WT.Debug.error("Aborting product: "+a,"011");WT.Debug.error("LOADER Error","011",b)};this.Event=function(a,b,c,h){a&&
(a=a.toLowerCase());this.name=a;this.handler=null;this.state=WT.Event.STATUS_UNKNOWN;b&&(this.state=b);this.target=c;this.params={};h&&(this.params=h)};this.EventEngineClass=function(){var a={},b={},c=function(a,b,c,l){p&&!l&&e.Debug.error("fireEvent: Loader global abort, Aborted due to prior error, check error message for details.","012",null,"LOADER");b.handler=a;b.params.eventID=(new Date).getTime();e.Debug.trace("fireEvent: [name: "+b.name+"], state:"+b.state+("undefined"!==typeof c?", async["+
c+"]":", async not set"),"LOADER");e.Debug.superfine("function:"+b.handler.toString()+"]","LOADER");c?setTimeout(function(a,b){return function(){a(b)}}(a,b),0):b.handler(b);return 1};a.addEventHandler=function(a,g,d,l){if(!a||!g&&!d)return e.Debug.debug("events: Can not add event handler, missing name or listeners. ","LOADER"),-1;a=a.toLowerCase();b[a]||(b[a]={});b[a].success||(b[a].success=[]);b[a].fault||(b[a].fault=[]);var m=!1;if(g){for(var m=!1,q=0;q<b[a].success.length;q++)if(e.hasVal(b[a].success[q])&&
b[a].success[q].toString()===g.toString()&&!0!==l){m=!0;break}m||(b[a].success.push(g),e.Debug.superfine("addEventHandler success handler"+b[a].success.length+" for "+a+"\nhandler\x3d"+g.toString(),"LOADER"))}var f=m?0:1;if(d){m=!1;for(q=0;q<b[a].fault.length;q++)if(e.hasVal(b[a].fault[q])&&b[a].fault[q].toString()===d.toString()&&!0!==l){m=!0;break}m||(b[a].fault.push(d),e.Debug.superfine("addEventHandler fault handler"+b[a].fault.length+" for "+a+"\nhandler\x3d"+g.toString(),"LOADER"))}f+=m?0:1;
if(b[a].queue&&0!==b[a].queue.length)for(q=b[a].queue.length-1;0<=q;q--)l=b[a].queue[q],g&&"success"===l.event.state?c(g,l.event,l.async,l.override):d&&"fault"===l.event.state&&c(d,l.event,l.async,l.override),b[a].queue.splice(q,1);return f};a.removeEventHandler=function(a,c,d){if(!a)return e.Debug.trace("LOADER removeEventHandler:  events: Can not remove event handler, missing event name."),-1;a=a.toLowerCase();if(!b[a])return 0;if(!c&&!d)return delete b[a],0;var l=0;if(c)for(var m=0;m<b[a].success.length;m++)if(e.hasVal(b[a].success[m])&&
b[a].success[m].toString()==c.toString()){b[a].success.splice(m,1);l=1;break}if(d)for(c=0;c<b[a].fault.length;c++)if(e.hasVal(b[a].fault[c])&&b[a].fault[c].toString()==d.toString()){b[a].fault.splice(m,1);l++;break}return l};a.fireEvent=function(a,g,d,l){if(p&&!d)return e.Debug.error("fireEvent: Loader global abort, Aborted due to prior error, check error message for details.","012",null,"LOADER"),a.name?e.Debug.error("fireEvent(event\x3d'"+a.name+"'): g_loaderAborted due to prior error, check error message for details.",
"012",null,"LOADER"):e.Debug.error("fireEvent: Aborted due to prior error, check error message for details.","012"),-1;var m=a.name,q=a.state,f=b[m]?!0:!1,n=f&&b[m][q]?!0:!1,k=f&&b[m].queue?!0:!1;if(n&&0!==b[m][q].length||!l){if(!f)return e.Debug.trace("fireEvent: [name: "+m+"], no registered event was found","LOADER"),-1;if(!n)return e.Debug.trace("fireEvent: [name:"+m+", state:"+q+"] no event handler was found","LOADER"),-1}else return e.Debug.trace("fireEvent: [name: "+m+"], no registered event was found, enqueueing",
"LOADER"),f||(b[m]={}),k||(b[m].queue=[]),b[m].queue.push({event:a,async:g,override:d}),0;l=b[m][q];for(n=f=0;n<l.length;n++)if(l[n])try{c(l[n],a,g,d),f++}catch(s){e.Debug.error("Unhandled Event Exception, [name: "+m+", state: "+q+", function: "+a.handler.toString()+"]","013",s)}return f};a.getEventHandlers=function(){return b};a.length=function(){var a=0,c;for(c in b)b.hasOwnProperty(c)&&a++;return a};a.addFireOnce=function(b,c,d){var e=function(){c();a.removeEventHandler(b,e,d)};a.addEventHandler(b,
e,d)};a.clearAllEventHandlers=function(){b={}};return a};k=new this.EventEngineClass;this.addEventHandler=k.addEventHandler;this.removeEventHandler=k.removeEventHandler;this.fireEvent=k.fireEvent;this.addFireOnce=k.addFireOnce;this.clearAllEventHandlers=k.clearAllEventHandlers;this.Event.PREINIT="preinit";this.Event.INIT="init";this.Event.PRELOAD="preload";this.Event.LOAD="load";this.Event.POSTLOAD="postload";this.Event.LOADER_ABORT="loader_abort";this.Event.LOADER_MODULE_ABORT="loader_module_abort";
this.Event.LOADER_CLICK="loader_click";this.Event.LOADER_PRE_EXECUTE="loader_pre_execute";this.Event.LOADER_EXECUTE="loader_execute";this.Event.LOADER_RESET="loader_reset";this.Event.LOADER_COLLECT="loader_collect";this.Event.LOADER_VIEW="loader_view";this.Event.DEBUGGER_CLEAR_COOKIES="debugger_clear_cookies";this.Event.DEBUGGER_DUMP_PARAMS="debugger_dump_params";this.Event.DEBUG_ERROR_OUT="debug_error_out";this.Event.DOM_READY="dom_ready";this.Event.DOM_ONLOAD="dom_onload";this.Event.TIMER_EXPIRE=
"timer_expire";this.Event.TIMER_CLEAR="timer_clear";this.Event.STATUS_SUCCESS="success";this.Event.STATUS_FAULT="fault";this.Event.STATUS_UNKNOWN="unknown";this.Event.OPT_LOAD_COMPLETE="opt_load_complete";this.Event.HIDESHOW="hide_show";this.Event.OPT_COMPLETE="opt_complete";this.Event.OPT_PRODUCT_READY="opt_product_ready";this.Event.OPT_PV_MUTATE="opt_pv_mutate";this.Event.PAGEVIEW="pageview";this.Event.CONVERSION="conversion";this.Event.DEBUGGER_CHECK_MODE="debugger_check_mode";this.Event.ANA_LOAD_COMPLETE=
"ana_load_complete";this.Event.ANA_PLUGINS_LOADED="ana_plugins_loaded";this.Event.ANA_PLUGINS_INIT="ana_plugins_init";this.Event.ANA_DCS_SETUP="ana_dcs_setup";this.Event.ANA_PRODUCT_READY="ana_product_ready";this.Event.ANA_SETUP_COMPLETE="ana_setup_complete";this.Event.ANA_BEFORE_PAGE_ANALYSIS="ana_before_page_analysis";this.Event.ANA_AFTER_PAGE_ANALYSIS="ana_after_page_analysis";this.Event.ANA_BEFORE_GETID="ana_before_getid";this.Event.ANA_AFTER_GETID="ana_after_getid";this.Event.ANA_PV_MUTATE="ana_pv_mutate";
this.Event.COMMON_LOAD_COMPLETE="common_load_complete";this.Event.COMMON_PLUGINMGR_READY="common_pluginmgr_ready";this.Event.COMMON_TRACKING_FLUSH="common_tracking_flush";this.Event.COMMON_COM_EXEC_REQ="common_com_exec_req";this._Debug=function(){var a=-1;this._shutdown=!1;var b=[],c=this,d=function(c,d,e){e&&(d=e+":  "+d);this._shutdown||b.push([c,d]);if(this._shutdown)b=[];else if(!(a<c)&&"undefined"!==typeof console&&console){e=!0;switch(c){case 0:console.error&&(console.error(d),e=!1);break;case 1:console.warn&&
(console.warn(d),e=!1);break;case 2:console.info&&(console.info(d),e=!1);break;case 3:case 4:case 5:console.log&&(console.log(d),e=!1)}!0===e&&console.log&&console.log(d)}};c.superfine=function(a,b){d(5,a,b)};c.trace=function(a,b){d(4,a,b)};c.debug=function(a,b){d(3,a,b)};c.info=function(a,b){d(2,a,b)};c.error=function(a,b,c,e){var f="";c&&("string"===typeof c?f="\n"+c:c.toString?(f=c.toString(),c.stack&&(f+=", [stack]: "+c.stack)):f="\n"+(c.message?c.message:"")+(c.name?" ["+c.name+"]":"")+(c.fileName?
"\n ("+c.fileName+":"+c.lineNumber+")\n"+c.stack:""));d(0,(b?b+": ":"")+a+f,e);WT.fireEvent(new WT.Event(WT.Event.DEBUG_ERROR_OUT,WT.Event.STATUS_SUCCESS,c))};c.dir=function(a,b,e){b&&d(2,b,e);console&&"function"===typeof console.dir?console.dir(a):c.dirStr(a)};c.dirStr=function(a,b){a=a||{};b=b||"";for(var d in a)a.hasOwnProperty(d)&&"function"!==typeof a[d]&&c.debug("\t"+d+" : "+a[d],b)};c.setDebugLevel=function(b){a=b};c.getDebugLevel=function(){return a};c.clearCookies=function(){WT.fireEvent(new WT.Event(WT.Event.DEBUGGER_CLEAR_COOKIES,
WT.Event.STATUS_SUCCESS))};c.dumpParams=function(){var a=c.getConfigParams();a.loader&&c.dir(a.loader,"Config parameters","Loader");a.analytics&&c.dir(a.analytics,"Config parameters","Analytics");a.optimize&&c.dir(a.optimize,"Config parameters","Optimize");return a};c.getConfigParams=function(){var a={loader:null,optimize:null,analytics:null};a.loader={version:x,versionStr:[x.major,x.minor,x.inc].join(".")};s.analytics&&(a.analytics=WT.hasVal(s.analytics.getConfigParams)?s.analytics.getConfigParams():
{});s.optimize&&(a.optimize=WT.hasVal(s.optimize.getParams)?s.optimize.getParams():{});return a};c.checkMode=function(a){WT.fireEvent(new WT.Event(WT.Event.DEBUGGER_CHECK_MODE,WT.Event.STATUS_SUCCESS,{resetFlag:a}))};c.getHistory=function(){return b}};var N=function(a,b){this._name=a;this._state=b;this._met=!1},u=function(a,b,c){var h=this,g={},f=[];this.prodId=a;this.plugin=new b;this.executeState=u.WAITING;this.stopTime=this.startTime=this.timer=null;this.contextName="default";"undefined"!==typeof c&&
(this.contextName=c);this.putDependency=function(a){g[a._name]=a};this.reset=function(){h.executeState=u.WAITING;g={};f=[]};this.clearDependencies=function(){g={}};this.getDependency=function(a){for(var b in g)if(g.hasOwnProperty(b)&&g[b]._name===a)return g[b];return null};this.getDependents=function(){0==f.length&&(f=WT.getDependents(h.prodId));return f};this.updateDependents=function(){f=WT.getDependents(h.prodId)};this.getExecuteState=function(){return this.executeState};this.hasMetDeps=function(){for(var a in g)if(g.hasOwnProperty(a)&&
""!==a&&!0!==g[a]._met)if(d[a].getExecuteState()===g[a]._state)g[a]._met=!0;else return!1;return!0};this.updateDependencyState=function(a,b){var c=h.getDependency(a);null!==c&&c._state===b&&(c._met=!0)};this._startTimer=function(a){this.timer?e.Debug.info("LOADER:  "+this.prodId+" timer already started, using current timer."):(e.Debug.debug("LOADER:  starting timer for "+h.prodId),this.timer=setTimeout(function(){e.Debug.error("LOADER:  "+h.prodId+"module timer expired calling Abort","015");e.fireEvent(new WT.Event(h.prodId+
"_"+WT.Event.TIMER_EXPIRE,WT.Event.STATUS_SUCCESS));e.fireEvent(new WT.Event(h.prodId+"_"+WT.Event.LOADER_MODULE_ABORT,WT.Event.STATUS_SUCCESS))},a),this.startTime=new Date,e.Debug.info("LOADER:  "+this.prodId+" timer started ["+this.startTime+"]."))};this._clearTimer=function(){this.stopTime=new Date;this.timer&&(clearTimeout(this.timer),this.timer=null);e.Debug.info("LOADER:  "+this.prodId+" timer cleared ["+this.stopTime+"]")};this.tryExecPostload=function(){var a=h.getExecuteState()===u.READY,
b=h.hasMetDeps(),c="undefined"!==typeof h.plugin[WT.Event.POSTLOAD];if(b&&a&&c)return e.Debug.debug("setExecuteState:  '"+h.prodId+"' has met all dependencies \x26\x26 ready, running postload"),h.plugin[WT.Event.POSTLOAD](),!0;if(b&&a&&!c)return WT.Debug.superfine(h.prodId+", has no postLoad section"),!0;WT.Debug.superfine(h.prodId+", did not meet postload exec conditionals");return!1}};u.WAITING="waiting";u.DOWNLOADING="downloading";u.READY="ready";u.RUNNING="running";u.ABORTED="aborted";var d={};
this.registerPlugin=function(a,b){d[a.ProductName]=new u(a.ProductName,a,b);d[a.ProductName].executeState=u.WAITING;WT.hasVal(a.prototype.abort)&&WT.addEventHandler(a.ProductName+"_"+WT.Event.LOADER_MODULE_ABORT,a.prototype.abort);if(WT.hasVal(a.prototype.wtConfigObj.s_dependencies))for(var c=a.prototype.wtConfigObj.s_dependencies.split(","),e=0;e<c.length;e++){var g=[],g=c[e].split(":");d[a.ProductName].putDependency(new N(g[0],g[1]))}for(var f in d)d.hasOwnProperty(f)&&d[f].updateDependents();a.prototype&&
a.prototype.wtConfigObj&&a.prototype.wtConfigObj.s_useTrackingPipeline&&!0===a.prototype.wtConfigObj.s_useTrackingPipeline&&(d[a.ProductName].useTrackingPipeline=!0,c=a.prototype.wtConfigObj,WT.hasVal(c.s_pageTimeout)&&WT.hasVal(c.s_TrackingPipelineTimeout)?d[a.ProductName].s_TrackingPipelineTimeout=Math.max(c.s_pageTimeout,c.s_TrackingPipelineTimeout):WT.hasVal(c.s_pageTimeout)?d[a.ProductName].s_TrackingPipelineTimeout=c.s_pageTimeout:WT.hasVal(c.s_TrackingPipelineTimeout)&&(d[a.ProductName].s_TrackingPipelineTimeout=
c.s_TrackingPipelineTimeout))};this.clearPlugins=function(){d={}};this.hasMetDeps=function(a){return d[a].hasMetDeps()};this.getDependents=function(a){var b=[],c;for(c in d)d.hasOwnProperty(c)&&null!==d[c].getDependency(a)&&b.push(c);return b};this.updateDependencies=function(a,b){if(!a||!d[a])return null;if(!b)return d[a].clearDependencies(),null;var c=b.split(",");if(!c||0==c.length)return null;d[a].clearDependencies();for(var e=0;e<c.length;e++)if(nameToState=c[e].split(":"),2===nameToState.length)d[a].putDependency(new N(nameToState[0],
nameToState[1]));else return null};var O=function(a){var b=d[a];if(b.tryExecPostload()){b.executeState="running";a=b.getDependents(a);for(var c in a)a.hasOwnProperty(c)&&O(a[c])}};this.setExecuteState=function(a,b){if(b===WT.Event.LOADER_MODULE_ABORT)d[a].executeState=u.ABORTED;else if(e.getExecuteState(a)!==WT.Event.LOADER_MODULE_ABORT){d[a].executeState=b;e.Debug.trace("setExecuteState:  '"+a+"' to '"+b+"'");var c=d[a].getDependents(),h;for(h in c)c.hasOwnProperty(h)&&d.hasOwnProperty(c[h])&&d[c[h]].updateDependencyState(a,
b);O(a)}};this.getExecuteState=function(a){return WT.hasVal(d[a])?d[a].executeState===u.ABORTED?WT.Event.LOADER_MODULE_ABORT:d[a].executeState:null};this.isDependency=function(a){for(var b in d)if(d.hasOwnProperty(b)&&null!==d[b].getDependency(a))return e.Debug.trace("isDependency:  '"+a+"' is dependency of '"+b+"'"),!0;e.Debug.trace("isDependency:  '"+a+"' is not a dependency of any product");return!1};this.getTrackingPipelineProducts=function(){var a=[],b;for(b in d)if(d.hasOwnProperty(b)&&d[b].useTrackingPipeline){var c=
{};c.name=b;d[b].s_TrackingPipelineTimeout&&(c.timeout=d[b].s_TrackingPipelineTimeout);a.push(c)}return a};this.getContextUrl=function(a,b){return"//c.webtrends.com/acs/account/247wntkj6g/js/"+a+"-"+b+".js"};this.getProduct=function(a){for(var b in d)if(d.hasOwnProperty(b)&&a==d[b].prodId)return d[b];return null};this.isReady=function(){return J};this.isLoaded=function(){return D};this.addDOMEvent=function(a,b,c){try{return a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent(b,
c):eval("elm."+b+"\x3dfunc;"),0}catch(d){return-1}};this.removeDOMEvent=function(a,b,c){try{return a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent(b,c),0}catch(d){return-1}};this.getSafeEventName=function(a,b){var c=b.substr(0,2);if(a.addEventListener){if("on"===c)return b.substring(2)}else if(a.attachEvent&&"on"!==c)return"on"+b;return b};this.regPlugin=function(a,b,c){var d=function(){WT.Debug.debug("regPlugin - call of deferred register of "+a,"LOADER");WT.common.pluginMgr.regPlugin(a,
b,c)};WT.common&&WT.common.pluginMgr&&WT.common.pluginMgr.isReady&&!0===WT.common.pluginMgr.isReady()?(WT.Debug.debug("WT.common.pluginMgr exists so register is possible"),d()):(WT.Debug.debug("regPlugin - deferred register of "+a,"LOADER"),WT.addEventHandler(WT.Event.COMMON_PLUGINMGR_READY,d,null,!0))};this.hideAndShow=function(a,b,c,d){try{if((WT.hasVal(a)||"shift"==b||y)&&WT.hasVal(b)&&WT.hasVal(c)){e.Debug.debug("hideAndShow:  "+(y?"tag 'inHead'":"tag 'not inHead'")+", "+(c?"showing":"hiding")+
" '"+(a&&a.nodeName?a.nodeName:"unnamed elem")+"' with type '"+b+"'");var g=function(a){c?WT.removeStyleSheet("wt_StyleSheet"):WT.applyStyleSheet(a,"wt_StyleSheet")};if("display"==b)y?g("body{ display: none !important}"):(a.style.display=c?"":"none",a==n.body||c||(n.body.style.display=""));else if("visibility"==b)y?g("body{ visibility: hidden !important}"):(a.style.visibility=c?"visible":"hidden",a.style.hidden=!c,a==n.body||c||(n.body.style.visibility="visible",n.body.style.hidden=!1));else if("shift"==
b||"supershift"==b)if(!c){var f=n.getElementsByTagName("head")[0];style=n.createElement("style");style.type="text/css";style.id="wt_shiftStyle";style.styleSheet?style.styleSheet.cssText="body{position:absolute !important; left: -1000% !important; visibility: hidden}":style.appendChild(n.createTextNode("body{position:absolute !important; left: -1000% !important;}"));f.appendChild(style)}else{if(c){var l=n.getElementById("wt_shiftStyle");l&&l.parentNode.removeChild(l)}}else if("overlay"==b){var m=n.getElementById("wt_overlay"),
k=n.getElementById("wt_overlayStyle"),s=e.hasVal(d)?d:"#ffffff";if(c&&m)m.parentNode.removeChild(m),k&&k.parentNode.removeChild(k);else if(!c&&!m){y&&e.Debug.error("hideAndShow:  Warning! wt tag detected in head, overlay mode may error out or cause flickering","007");if(!k){var v=n.createElement("style");v.setAttribute("type","text/css");v.setAttribute("id","wt_overlayStyle");g="#wt_overlay{position:absolute;width:100%;height:100%;top:0px;right:0px;bottom:0px;left:0px;background-color:"+s+";z-index:2147483646}";
v.styleSheet?v.styleSheet.cssText=g:v.appendChild(n.createTextNode(g));n.getElementsByTagName("head")[0].appendChild(v)}e.hasVal(d)?m=n.createElement("div"):(m=n.createElement("iframe"),m.frameBorder=0);m.id="wt_overlay";n.getElementsByTagName("body")[0].appendChild(m)}}else"none"==b?e.Debug.trace("LOADER: type: none"):e.Debug.debug("hideAndShow did not contain a matching type, so not hiding/showing");d={};d.displayType=b;d.display=c;WT.fireEvent(new WT.Event(WT.Event.HIDESHOW,WT.Event.STATUS_SUCCESS,
a,d))}else e.Debug.error("hideAndShow param list incomplete","006")}catch(r){WT.Debug.error("Failure in hide/show functionality.  Verify valid HTML syntax","008",r)}};var P=function(){try{if(document.addEventListener&&("complete"!==document.readyState&&"undefined"!==typeof document.readyState||w(),document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,!1);w()},!1),/WebKit|Opera/i.test(navigator.userAgent)))var a=setInterval(function(){/loaded|complete/.test(document.readyState)&&
(clearInterval(a),w())},10);document.attachEvent&&("complete"!==document.readyState&&"loading"!==document.readyState||w(),document.attachEvent("onreadystatechange",function(){if("complete"===document.readyState||"loading"===document.readyState)document.detachEvent("onreadystatechange",arguments.callee),w()}));window.addEventListener?window.addEventListener("load",function(){window.removeEventListener("load",arguments.callee,!1);w()},!1):window.attachEvent&&window.attachEvent("onload",function(){window.detachEvent("onload",
arguments.callee,!1);w()});D?E():window.addEventListener?window.addEventListener("load",function(){window.removeEventListener("load",arguments.callee,!1);E()},!1):window.attachEvent&&window.attachEvent("onload",function(){window.detachEvent("onload",arguments.callee,!1);E()})}catch(b){w(),E()}};e.Debug=new e._Debug;y=function(){try{var a=n.getElementsByTagName("script");return"HEAD"==a[a.length-1].parentNode.nodeName?!0:!1}catch(b){return WT.Debug.error("inHead: Failed to detect if in head, assuming inHead",
"001",b),!0}}();e.isBodyExtant();var A=this.parseQueryString(f);f=function(a,b){e.hasVal(A[a])&&e.hasVal(b)&&b(A[a])};e.hasVal(A)&&(f("_wt.accountRoot",function(a){accountRoot=a}),f("_wt.s_jsonUrl",function(a){}),f("_wt.debug",function(a){e.Debug.setDebugLevel(a.length)}));var K=function(a){var b={};a=a.split(";");for(var c in a)if(a.hasOwnProperty(c)){var d=a[c].split(":");b[d[0]]=d[1]}return b},t=function(){if(null!==A&&A["_wt.context"])return K(A["_wt.context"]);var a;a:{a=document.cookie.split(";");
for(var b=0;b<a.length;b++){var c=[];c[0]=a[b].substring(0,a[b].indexOf("\x3d"));for(c[1]=a[b].substring(a[b].indexOf("\x3d")+1);" "===c[0].charAt(0);)c[0]=c[0].substring(1,c[0].length);if("_wt.context"==c[0]){a=c[1];break a}}a=null}if("undefined"!==typeof a&&null!==a)return K(a);a:{a=document.getElementsByTagName("meta");for(b=0;b<a.length;b++)if("_wt.context"==a[b].name){a=a[b].content;break a}a=null}if("undefined"!=typeof a&&null!==a)return K(a)}();if("undefined"!==typeof t){e.Debug.info("LOADER:  Found one or more context(s)");
for(var L in t)t.hasOwnProperty(L)&&e.Debug.trace("LOADER:  triggers have set contextTriggerMap '"+L+"':'"+t[L]+"'")}var B=function(a){e.Debug.error("Loader Error: "+a,"016")};e.Debug.info("LOADER:  Version "+[x.major,x.minor,x.inc].join("."));this.addEventHandler(this.Event.PREINIT,function(){try{for(var a in d)d.hasOwnProperty(a)&&WT.hasVal(d[a].plugin)&&WT.hasVal(d[a].plugin[WT.Event.PREINIT])&&F(a)&&WT.getExecuteState(a)!==WT.Event.LOADER_MODULE_ABORT&&(e.Debug.trace("LOADER:  product '"+a+"' with context name '"+
d[a].contextName+"' _preinit phase start"),d[a].plugin[WT.Event.PREINIT](),e.Debug.trace("LOADER:  product '"+a+"' with context name '"+d[a].contextName+"' _preinit phase complete"))}catch(b){WT.abortModuleHelper(a,b)}},function(){B("preinit fail")});this.addEventHandler(this.Event.INIT,function(){try{for(var a in d)d.hasOwnProperty(a)&&WT.hasVal(d[a].plugin)&&WT.hasVal(d[a].plugin[WT.Event.INIT])&&F(a)&&WT.getExecuteState(a)!==WT.Event.LOADER_MODULE_ABORT&&(e.Debug.trace("LOADER:  product '"+a+"' with context name '"+
d[a].contextName+"' _init phase start"),d[a].plugin[WT.Event.INIT](),e.Debug.trace("LOADER:  product '"+a+"' with context name '"+d[a].contextName+"' _init phase complete"))}catch(b){WT.abortModuleHelper(a,b)}},function(){B("init fail")});this.addEventHandler(this.Event.PRELOAD,function(){try{for(var a in d)d.hasOwnProperty(a)&&WT.hasVal(d[a].plugin)&&WT.hasVal(d[a].plugin[WT.Event.PRELOAD])&&WT.hasVal(d[a].plugin.wtConfigObj)&&!0===d[a].plugin.wtConfigObj.doLoad&&F(a)&&WT.getExecuteState(a)!==WT.Event.LOADER_MODULE_ABORT&&
(e.Debug.trace("LOADER:  product '"+a+"' with context name '"+d[a].contextName+"' _preload phase start"),d[a].plugin[WT.Event.PRELOAD](),e.Debug.trace("LOADER:  product '"+a+"' with context name '"+d[a].contextName+"' _preload phase complete"))}catch(b){WT.abortModuleHelper(a,b)}},function(){B("preload fail")});this.addEventHandler(this.Event.LOAD,function(){try{for(var a in d)d.hasOwnProperty(a)&&WT.hasVal(d[a].plugin)&&WT.hasVal(d[a].plugin[WT.Event.LOAD])&&WT.hasVal(d[a].plugin.wtConfigObj)&&!0===
d[a].plugin.wtConfigObj.doLoad&&F(a)&&WT.getExecuteState(a)!==WT.Event.LOADER_MODULE_ABORT&&(WT.setExecuteState(a,u.DOWNLOADING),e.Debug.trace("LOADER:  product '"+a+"' with context name '"+d[a].contextName+"' _load phase start"),d[a].plugin[WT.Event.LOAD](function(a){return function(){WT.Debug.debug(a+" downloaded successfully")}}(a)),e.Debug.trace("LOADER:  product '"+a+"' with context name '"+d[a].contextName+"' _load phase complete"))}catch(b){WT.abortModuleHelper(a,b)}},function(){B("load fail")});
this.addEventHandler(this.Event.LOADER_ABORT,function(){p=!0;e.Debug.error("Loader global abort event","017");try{for(var a in d)d.hasOwnProperty(a)&&WT.hasVal(d[a].plugin)&&!0===d[a].plugin.wtConfigObj.doLoad&&(WT.fireEvent(new WT.Event(a+"_"+WT.Event.LOADER_MODULE_ABORT,WT.Event.STATUS_SUCCESS),!1,!0),WT.setExecuteState(a,WT.Event.LOADER_MODULE_ABORT),WT.clearTimer(a),WT.Debug.error("Aborting product: "+a,"018"))}catch(b){WT.abortModuleHelper(a,b)}},function(){B("abort fail")});this.start=function(){try{P();
var a=function(){e.fireEvent(new WT.Event(WT.Event.PREINIT,WT.Event.STATUS_SUCCESS));e.fireEvent(new WT.Event(WT.Event.INIT,WT.Event.STATUS_SUCCESS));e.fireEvent(new WT.Event(WT.Event.PRELOAD,WT.Event.STATUS_SUCCESS));e.fireEvent(new WT.Event(WT.Event.LOAD,WT.Event.STATUS_SUCCESS));e.Debug.debug("LOADER:  Synchronous functionality has finished firing")};if(WT.hasVal(t)){e.Debug.debug("LOADER:  contextTriggerMap contains contexts");var b=[],c;for(c in t)if(t.hasOwnProperty(c)){var d=e.getContextUrl(c,
t[c]);"undefined"!==typeof d&&(e.Debug.debug("LOADER:  adding "+d+" to download"),b.push(d))}e.downloadLibs("head",a,0,!0,b)}else a()}catch(g){e.fireEvent(new WT.Event(WT.Event.LOADER_ABORT,WT.Event.STATUS_SUCCESS))}};e.Debug.debug("WT object created","LOADER");e.Debug.info("To clear Optimize cookies use: 'WT.Debug.clearCookies()'");e.Debug.info("To dump config params use: 'WT.Debug.dumpParams()'");e.Debug.info("To check the mode use: 'WT.Debug.checkMode(false)' - Use true if you wish to reset the mode.")}
"undefined"==typeof WT&&(WT=new s(window,window.document,window.navigator,window.location))})(window,window.document,window.navigator,window.location);WT.sizzleModule=function(){};WT.sizzleModule.prototype.wtConfigObj={libUrl:"//c.webtrends.com/acs/common/js/lib/sizzle.min.js",doLoad:!0,s_dependencies:""};
WT.sizzleModule.prototype.load=function(f){try{WT.updateDependencies("sizzle",this.wtConfigObj.s_dependencies),"undefined"!=typeof Sizzle&&WT.hasVal(Sizzle)||!WT.isDependency("sizzle")?WT.setExecuteState("sizzle","ready"):WT.downloadLib("head",f,function(){WT.abortModuleHelper("sizzle","failed to download sizzle");WT.abortModuleHelper("optimize","failed to download sizzle")},0,!0,this.wtConfigObj.libUrl)}catch(k){WT.abortModuleHelper("optimize",k)}};WT.sizzleModule.prototype.postload=function(){};
WT.sizzleModule.ProductName="sizzle";WT.registerPlugin(WT.sizzleModule,"default");WT.jsonModule=function(){};WT.jsonModule.prototype.wtConfigObj={libUrl:"//c.webtrends.com/acs/common/js/lib/json2.js",doLoad:!0};
WT.jsonModule.prototype.load=function(f){try{WT.updateDependencies("json",this.wtConfigObj.s_dependencies),"undefined"===typeof JSON&&WT.isDependency("json")?(WT.Debug.debug("JSON not detected"),s_jsonLoaded=!1,WT.downloadLib("head",f,function(){WT.abortModuleHelper("json","failed to download json");WT.abortModuleHelper("optimize","failed to download json");WT.abortModuleHelper("analytics","failed to download json")},0,!0,this.wtConfigObj.libUrl)):(s_jsonLoaded=!0,WT.setExecuteState("json","ready"))}catch(k){WT.abortModuleHelper("optimize",
k),WT.abortModuleHelper("analytics",k)}};WT.jsonModule.prototype.postload=function(){};WT.jsonModule.ProductName="json";WT.registerPlugin(WT.jsonModule,"default");WT.commonModule=function(){};WT.commonModule.prototype.wtConfigObj={libUrl:"//c.webtrends.com/acs/common/js/0.0.1/common.js",doLoad:!0,s_dependencies:"json:running"};
WT.commonModule.prototype.load=function(f){try{(!WT.hasVal(WT.common)||WT.hasVal(WT.common)&&!WT.hasVal(WT.common.TrackingPipeline))&&WT.isDependency("common")&&WT.downloadLib("head",f,function(){WT.fireEvent(new WT.Event("common"+WT.Event.LOADER_MODULE_ABORT,WT.Event.STATUS_SUCCESS))},0,!0,this.wtConfigObj.libUrl)}catch(k){WT.abortModuleHelper("common",k)}};WT.commonModule.prototype.postload=function(){WT.common.setup()};WT.commonModule.ProductName="common";WT.registerPlugin(WT.commonModule,"default");
WT.optimizeModule=function(){};
WT.optimizeModule.prototype.wtConfigObj={alwaysLoad:!0,s_keyToken:"14d3f67c5dccfe393d04325c673432ce4c030021120b",doLoad:!1,s_loaderHide:!0,s_pageTimeout:1E4,s_dependencies:"sizzle:ready,json:ready,common:running",domId:"body",s_pageDisplayMode:"none",defaultCollectionServer:"scs.webtrends.com",s_useTrackingPipeline:!0,s_domainKey:1654062,libUrl:"//c.webtrends.com/acs/common/product/optimize/js/4.2/optimize.js",enableCORS:!0,accountGuid:"247wntkj6g",s_otsServer:"ots.optimize.webtrends.com",s_pageMode:"head",
s_TrackingPipelineTimeout:4E3};
WT.optimizeModule.prototype.preinit=function(){try{WT.Debug.debug("PREINIT: Executing Preinit script");WT.optimizeModule.prototype.checkWhitelist=function(){var f,k,r;r=[/[\?&]_wt.testWhitelist=true/i,/europassistance.it\/europassistance\/registrati\/(polizza|bundlepolizza)\/sceltapagamento/,/(ecommercecoll|ecommerce).apps.europassistance.it\/Registrati\/(polizza|bundlepolizza)\/sceltapagamento/,/(ecommercecoll|ecommerce).apps.europassistance.it\/SP\/PCBox/,/europassistance.it\/europassistance\/registrati\/(bundlepreventivo|preventivo)\/beniassicurati/];for(f=
0;k=r[f];f++)if(document.location.href.match(k))return!0;return!1};var f={set:function(f,k,r,n,G){var p="";r?(p=new Date,p.setTime(p.getTime()+864E5*r),p="; expires\x3d"+p.toUTCString()):p="";sPath=n||"/";(r=G)||(r=document.domain,r=(r=r.match(/(^\w+$)|([^\.\s]+\.co\.[^\.\s]+$)|([^\.\s]+\.com\.[^\.\s]+$)|([^\.\s]+\.[^\.\s]+$)/))&&r[0]||document.domain);G=r;document.cookie=f+"\x3d"+encodeURIComponent(k)+p+"; path\x3d"+sPath+"; domain\x3d"+G},get:function(f){var k;f+="\x3d";for(var r=document.cookie.split(";"),
n=0;n<r.length;n++){for(var p=r[n];" "==p.charAt(0);)p=p.substring(1,p.length);if(0===p.indexOf(f))return k=p.substring(f.length,p.length),decodeURIComponent(k)}return null},del:function(f){this.set(f,"",-1)},has:function(f,k){var p=this.get(f);return!p||void 0!==k&&p!=k?!1:!0}},k=function(k){f.has("_wt.bdebug")&&console.log(k)};document.location.href.match(/europassistance\/account\/loginfull/)?(k("loginfull"),f.set("_wt.page","loginfull")):document.location.href.match(/tariffa\/proposta/i)?(k("proposta"),
f.set("_wt.page","proposta")):document.location.href.match(/registrati\/(bundlepreventivo|preventivo)\/beniassicurati/i)?(k("tuoDati"),f.set("_wt.page","tuoDati")):document.location.href.match(/registrati\/(polizza|bundlepolizza)\/sceltapagamento/i)?(k("aquista"),f.set("_wt.page","aquista")):document.location.href.match(/registrati\/(polizza|bundlepolizza|membership)\/pagamentoeffettuato/i)?(k("grazie"),f.set("_wt.page","grazie")):document.location.href.match(/(ecommercecoll|ecommerce).apps.europassistance.it\/account\/loginfull/i)?
k("iframe"):document.location.href.match(/(ecommercecoll|ecommerce).apps.europassistance.it\/Registrati\/(polizza|bundlepolizza)\/sceltapagamento/i)?k("iframe"):document.location.href.match(/(ecommercecoll|ecommerce).apps.europassistance.it\/SP\/PCBox/i)?k("iframe"):(k("delete"),f.del("_wt.page"))}catch(p){WT.abortModuleHelper("optimize",p)}};
WT.optimizeModule.prototype.init=function(){try{WT.optimizeModule.prototype.checkWhitelist()&&(this.wtConfigObj.s_pageDisplayMode="shift",this.wtConfigObj.s_pageTimeout=6E3,this.wtConfigObj.doLoad=!0),this.wtConfigObj.doLoad=this.wtConfigObj.doLoad||this.wtConfigObj.alwaysLoad}catch(f){WT.abortModuleHelper("optimize",f)}};
WT.optimizeModule.prototype.preload=function(){try{var f=0;WT.optimizeModule.prototype.wtConfigObj.s_conversionTimeout&&(f=WT.optimizeModule.prototype.wtConfigObj.s_conversionTimeout);WT.setLoaderConversionTimeoutDefault(Math.max(f,WT.loaderConversionTimeoutDefault()));WT.Debug.debug("PRELOAD:  Executing preload script");WT.updateDependencies("optimize",this.wtConfigObj.s_dependencies);if(WT.isBodyExtant()||"shift"===this.wtConfigObj.s_pageDisplayMode||WT.inHead()){var k=document.getElementsByTagName("body")[0];
WT.hideAndShow(k,this.wtConfigObj.s_pageDisplayMode,!1,this.wtConfigObj.overlayColor)}else{WT.Debug.debug("LOADER:  body element not found, hide via polling");var p=this.wtConfigObj.s_pageDisplayMode,v=this.wtConfigObj.overlayColor,s=this.wtConfigObj.s_pageTimeout;WT.pollForCondition(WT.isBodyExtant,function(){var f=document.getElementsByTagName("body")[0];!WT.hasVal(WT.optimize)||WT.hasVal(WT.optimize)&&!0!==WT.optimize.g_done?(WT.Debug.info("LOADER:  Optimize not done so hiding"),WT.hideAndShow(f,
p,!1,v)):WT.Debug.info("LOADER:  Optimize done flag so not hiding");WT.startTimer("optimize",s)})}}catch(r){WT.abortModuleHelper("optimize",r)}};WT.optimizeModule.prototype.load=function(f){try{WT.Debug.debug("LOAD:  Executing load phase"),WT.downloadLib("head",f,function(){WT.fireEvent(new WT.Event("optimize_"+WT.Event.LOADER_MODULE_ABORT,WT.Event.STATUS_SUCCESS))},0,!0,this.wtConfigObj.libUrl)}catch(k){WT.abortModuleHelper("optimize",k)}};
WT.optimizeModule.prototype.postload=function(){WT.Debug.debug("POSTLOAD:  Executing postload optimize complete");try{WT.Debug.info("LOADER:  WT.optimizeModule.prototype: postload"),WT.optimize.setup(WT.optimizeModule.prototype.wtConfigObj)}catch(f){WT.abortModuleHelper("optimize",f)}};
WT.optimizeModule.prototype.abort=function(){try{WT.Debug.debug("ABORT:  Executing optimizeModule abort");WT.Debug.error("WT.optimizeModule.prototype: abort",145,null,"LOADER");var f=WT.optimizeModule.prototype.wtConfigObj.s_pageDisplayMode;(WT.isBodyExtant()||"shift"===f||WT.inHead())&&WT.optimizeModule.prototype.wtConfigObj.s_loaderHide&&(WT.Debug.error("Optimize abort, so unhiding body ... ",146,null,"LOADER"),WT.hideAndShow(document.getElementsByTagName("body")[0],f,!0,WT.optimizeModule.prototype.wtConfigObj.overlayColor));
WT.setExecuteState("optimize",WT.Event.LOADER_MODULE_ABORT);WT.clearTimer(WT.optimizeModule.ProductName);WT.hasVal(WT.optimize)&&WT.hasVal(WT.optimize.g_Aborted)&&!1===WT.optimize.g_Aborted&&WT.fireEvent(new WT.Event(WT.Event.ABORT,WT.Event.STATUS_FAULT))}catch(k){WT.abortModuleHelper("optimize",k)}};WT.optimizeModule.ProductName="optimize";WT.registerPlugin(WT.optimizeModule,"Draft");WT.start();